name: Docker Build
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Get core
        uses: actions/checkout@v2
        with:
          ref: master
          path: core
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Get Frontend
        uses: actions/checkout@v2
        with:
          repository: iyear/pure-live-frontend
          ref: master
          path: frontend
      - name: Install and Build Frontend
        run: |
          mkdir static
          cd frontend
          yarn
          yarn run build
          mv dist ../core/static
          cd ../core
          tree
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: core/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            iyear/pure-live:latest
            iyear/pure-live:${{ steps.date.outputs.today }}